### ISSUE TITLE
no "main" field in package.json

### ISSUE THREAD

**Issue by substack** [SimonWaldherr/parseTime.js#25]
This package is on npm but there is no "main" field in package.json so that package can't be imported from node (or browserify) by just doing `require('parsetime')`.

**Comment by curioussavage** [comment]
Yeah this would be kinda nice. I'm just going to fork it and put it up on npm again with this added for anyone else that wants to use it.

**Comment by curioussavage** [comment]
my package is https://www.npmjs.com/package/time-parser if anyone wants to use it

**Comment by SimonWaldherr** [comment]
fixed, updated and published
